### ISSUE TITLE
Continue using separate repo for brigade.sh?

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade-www#47]
Do we wish to continue hosting the main landing page for brigade.sh in this separate repo?  Note that all of the official documentation is in brigadecore/brigade and the blog site at brigadecore/blog. Perhaps we like the flexibility of keeping the material in this repo separate.  I can also see folding the material in this repo into brigadecore/brigade itself.

For what it's worth, I don't see anything problematic with the current approach, just wanted to pose the question.

Thoughts @flynnduism @krancour ?

**Comment by krancour** [comment]
I see the www stuff as marketing / PR and think it should remain separate, but I'm happy to hear other perspectives.

**Comment by flynnduism** [comment]
I've tried both approaches in the past, seperate sites/repos/deploys per section vs merging everything into a single place; and I prefer this approach as it's cleaner to maintain - each section of the site has a different theme to suit (landing page / blog / docs layout) and it keeps things pretty lightweight

For Helm, we merged the sites and rebuilt the theme to accommodate the different layouts; it certainly can be done but I don't think having a single source was worth it, it certainly made the codebase more complicated overall

**Comment by vdice** [comment]
👍 Great, thank you for the feedback all.  Leaving as is!  Closing.
