### ISSUE TITLE
Brand refresh

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-www#54]
@flynnduism @vdice I think the two of you had been collaborating in the v2 branch (@flynnduism on design and @vdice on content) on a refreshed version of the site. Glancing at it, it looks like maybe it's not quite done yet. Just wondering about status and what we need to do to get it across the finish line. We're at risk right now of the site refresh blocking the v2 release.

**Comment by vdice** [comment]
Thanks for the reminder @krancour.  I revisited the main PR that led to the v2 branch (https://github.com/brigadecore/brigade-www/pull/49) and didn't see any specific content follow-ups, so I think we're good there.  Defer to @flynnduism on if further design/polish is needed.  Of course, definitely encourage reviewing the current content to see if it all looks good/ready: https://github.com/brigadecore/brigade-www/blob/v2/index.html

**Comment by flynnduism** [comment]
Vaughn's edits are in place but I need to finish applying the design updates, my goal was to do so this Friday and push but I can do so in a follow up PR if that's preferred

**Comment by krancour** [comment]
> but I can do so in a follow up PR if that's preferred

I don't think the updated content should go out before v2 is released. So there's no need to split it up into two things.

**Comment by krancour** [comment]
And thanks @flynnduism!

**Comment by krancour** [comment]
This will be closed by #57
