### ISSUE TITLE
wrong icon for mongodb

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-www#65]
Looks like this is the CosmosDB logo. This example used to read "Updated a CosmosDB database." When the text was changed, the icon was not.

We could either correct the icon or consider using an altogether different example.

![Screen Shot 2022-03-02 at 10 43 29 AM](https://user-images.githubusercontent.com/1821014/156396200-8939d0e0-61f4-4d41-a2f2-1edcd9cc3326.png)

**Comment by GermaVinsmoke** [comment]
Which generator you're using to generate these 14x14 images?

**Comment by krancour** [comment]
I'm not sure. That might be a question for @flynnduism.

**Comment by flynnduism** [comment]
I didn't use a generator, I think I photoshopped the icons to that size. 
I can update the icon to a MongoDB one:

![mongo-14](https://user-images.githubusercontent.com/686194/157123120-0005880e-09b4-42ea-a95d-6af8b427aedf.png)

**Comment by krancour** [comment]
This was addressed by #67. Closing.
