### ISSUE TITLE
Badly responsive elements in narrow resolutions

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade-www#7]
One of my monitors is in portrait mode, and it can't really be used to read the Brigade docs, as it's rendered as shown below:

![image](https://user-images.githubusercontent.com/13103165/55039320-54066880-502c-11e9-9e1e-203832785849.png)

It would be great if this was fixed, and maybe if the navigation on the left was hidden under a button or something for narrow screens.

By the way, the new docs theme is AWESOME!
Thanks!

cc @flynnduism

**Comment by flynnduism** [comment]
Thanks Radu. Will patch this css

**Comment by krancour** [comment]
This issue looks like it should have been for the main Brigade repo since that's where the docs are, but this also has been addressed already.
